In [1]:
def f(x):
    return -g(x)

In [1]:
4+5

9

In [2]:
import numpy as np

In [7]:
rt = np.arange(start=0,stop=10,step=0.1)

In [8]:
print(rt)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


In [9]:
rt.ndim

1

In [10]:
rt.shape

(100,)

In [11]:
arr = np.array([True,True,False],dtype=bool)

In [12]:
print(arr)

[ True  True False]


In [15]:
from numpy.linalg import norm
vector = np.array([1,-2,3])
print(norm(vector,ord=1))

6.0


In [16]:
print(norm(vector,ord=2))

3.7416573867739413


In [18]:
a = np.array([1,-2,3])
b = np.array([3,-4,8])
print(norm(a - b, ord=1))

9.0


In [21]:
a = a.reshape((3,1))
print(a)

[[ 1]
 [-2]
 [ 3]]


In [30]:
import scipy
print(scipy.spatial.distance.cdis(a,b,metric = 'euclidean'))

AttributeError: module 'scipy' has no attribute 'spatial'

In [35]:
a.reshape((1,3))
b.reshape((1,3))
a.shape
b.shape
print(np.dot(a,b))

ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

In [36]:
a.shape

(3, 1)

In [37]:
b.shape

(3,)

In [38]:
b.reshape((3,1))

In [39]:
b.shape

(3,)

In [40]:
a.reshape((3,))

array([ 1, -2,  3])

In [41]:
a.shape

(3, 1)

In [42]:
print(b)

[ 3 -4  8]


In [45]:
print(a)

In [46]:
a

array([[ 1],
       [-2],
       [ 3]])

In [47]:
b

array([ 3, -4,  8])

In [48]:
b.reshape(1,3)

array([[ 3, -4,  8]])

In [49]:
a.reshape(1,3)

array([[ 1, -2,  3]])

In [50]:
np.dot(a,b)

ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

In [51]:
a = a.reshape((1,3))
b = b.reshape((1,3))

In [52]:
np.dot(a,b)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [53]:
a

array([[ 1, -2,  3]])

In [54]:
b

array([[ 3, -4,  8]])